version: '3'
services:
  python-app:
    build: .
    ports:
      - "443:5000"
    volumes:
      - .:/app
      - /etc/letsencrypt/archive/{URL-domain}:/app/certs
    environment:
      - SSL_CERT_FILE=/app/certs/fullchain.pem
      - SSL_KEY_FILE=/app/certs/privkey.pem
    restart: unless-stopped
    
